languageCode = "en"
languageName = "English"
weight = 1
title = "Michelle Liao"

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  # logo = "img/logo.png"
  # secondaryLogo = "img/secondary-logo.png"
  # description = """My awesome website"""
  # copyright = """Copy, _right?_ :thinking_face:"""

[author]
  name = "Michelle Liao"
  image = "img/profile.jpg"
  headline = "Student"
  bio = "Hi. I'm Michelle, a high schooler at Quarry Lane"
  links = [
    { email = "mailto:michelleliao81@gmail.com" },
    { github = "https://github.com/mliao81" },
    { youtube = "https://www.youtube.com/@michelleliao4197" },
]

